import { DM_Sans } from "next/font/google";
import "./globals.css";
import Navber from "@/components/navber/Navber";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{background:'#171717'}} className={dmSans.className}>
      <Navber/>
      {children}
      </body>
    </html>
  );
}
